### ISSUE TITLE
PyAlarmTimer == ptimer?

### ISSUE THREAD

**Issue by keikoro** [amjith/PyAlarmTimer#1]
Say, is this the same thing as your [ptimer](http://amjith.blogspot.co.at/2010/09/pomodoro-timer-written-in-python-and.html) (which I found by browsing your website)?

Since there is no Readme or License file in your repo: what's the code's licence? I'm interested because I've been looking into creating my own Pomodoro timer and think it would help to be able to build upon someone else's code (especially as I'm more of a Python beginner...).

Thanks. (:

**Comment by amjith** [comment]
Hi, they are the same. But if you notice, the date stamp on those files was 5 years ago. I was in the same boat as you, learning python and looking for a Pomodoro timer. :)

I think started the code in google code. http://code.google.com/p/ptimer/ but then decided to move it to github (or maybe other way around). 

I'll be happy to add a license to the repo, if that'll be useful. I haven't looked at the code in a very long time and it probably isn't very pythonic. :(

**Comment by keikoro** [comment]
Aww, I don't mind the code not being very "pythonic", and I could still try to rewrite it... if I even get that far. (:

But yes, having a licence would be great so I know for sure what I can and cannot do with your code!

**Comment by amjith** [comment]
Done!

Added MIT license.

**Comment by keikoro** [comment]
Awesome, thank you! The next few days I'm still super busy with other things, but I'll have a look (and stab) at it afterwards, yay!
